#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

echo "Installing cmake files into $SPKG_LOCAL/share/qsnake/cmake"
mkdir -p "$SPKG_LOCAL"/share/qsnake
cp -r cmake "$SPKG_LOCAL"/share/qsnake/
echo "    Done."
